version: '3'

services:
    database:
        image: postgres:11-alpine
        environment:
            POSTGRES_USER: pgadminuser
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: guestbook_db
        ports: [5432]

    redis:
        image: redis:5-alpine
        ports: [6379]
        