version: '3'

services:
    database:
        image: postgres:11-alpine
        environment:
            POSTGRES_USER: pgadminuser
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: guestbook_db
        ports: [5432]

    redis:
        image: redis:5-alpine
        ports: [6379]

    rabbitmq:
        image: rabbitmq:3.7-management
        ports: [5672, 15672]

    mailer:
        image: schickling/mailcatcher
        ports: [1025, 1080]

    blackfire:
        image: blackfire/blackfire
        env_file: .env.local
        ports: [8707]
        